### ISSUE TITLE
devDependencies includes bootstrap 2

### ISSUE THREAD

**Issue by whispyy** [ovh-ux/ovh-utils-angular#8]
In bower.json there is bootstrap 2.X in dependencies.

New stack is supposed to be based on bootstrap 3. 
See : https://github.com/ovh-ux/ovh-manager-web/blob/master/bower.json

**Comment by antleblanc** [comment]
@whispyy `ovh-utils-angular` is a deprecated dependencie.

You can refer to this resolution used by the OVH Control Panel Web UI:
https://github.com/ovh-ux/ovh-manager-web/blob/master/bower.json#L99
